2017-09-23 19:05:40,363:INFO: Initializing tf session
2017-09-23 19:05:45,678:INFO: Epoch 1 out of 15
2017-09-23 19:11:12,197:INFO: acc 93.12 - f1 74.03
2017-09-23 19:11:14,552:INFO: - new best score!
2017-09-23 19:11:14,552:INFO: Epoch 2 out of 15
2017-09-23 19:17:10,403:INFO: acc 99.99 - f1 99.99
2017-09-23 19:17:14,000:INFO: - new best score!
2017-09-23 19:17:14,000:INFO: Epoch 3 out of 15
2017-09-23 19:23:34,739:INFO: acc 100.00 - f1 100.00
2017-09-23 19:23:37,829:INFO: - new best score!
2017-09-23 19:23:37,829:INFO: Epoch 4 out of 15
2017-09-23 19:28:50,907:INFO: acc 100.00 - f1 100.00
2017-09-23 19:28:53,371:INFO: - new best score!
2017-09-23 19:28:53,372:INFO: Epoch 5 out of 15
2017-09-23 19:33:56,144:INFO: acc 100.00 - f1 100.00
2017-09-23 19:33:58,551:INFO: - new best score!
2017-09-23 19:33:58,552:INFO: Epoch 6 out of 15
2017-09-23 19:39:04,841:INFO: acc 100.00 - f1 100.00
2017-09-23 19:39:07,594:INFO: - new best score!
2017-09-23 19:39:07,594:INFO: Epoch 7 out of 15
2017-09-23 19:44:26,285:INFO: acc 100.00 - f1 100.00
2017-09-23 19:44:28,716:INFO: - new best score!
2017-09-23 19:44:28,716:INFO: Epoch 8 out of 15
2017-09-23 19:49:54,262:INFO: acc 100.00 - f1 100.00
2017-09-23 19:49:56,700:INFO: - new best score!
2017-09-23 19:49:56,700:INFO: Epoch 9 out of 15
2017-09-23 19:55:20,870:INFO: acc 100.00 - f1 100.00
2017-09-23 19:55:23,556:INFO: - new best score!
2017-09-23 19:55:23,556:INFO: Epoch 10 out of 15
2017-09-23 20:00:15,588:INFO: acc 100.00 - f1 100.00
2017-09-23 20:00:17,820:INFO: - new best score!
2017-09-23 20:00:17,820:INFO: Epoch 11 out of 15
2017-09-23 20:04:42,143:INFO: acc 100.00 - f1 100.00
2017-09-23 20:04:44,337:INFO: - new best score!
2017-09-23 20:04:44,338:INFO: Epoch 12 out of 15
2017-09-23 20:09:07,770:INFO: acc 100.00 - f1 100.00
2017-09-23 20:09:10,292:INFO: - new best score!
2017-09-23 20:09:10,292:INFO: Epoch 13 out of 15
2017-09-23 20:13:51,911:INFO: acc 100.00 - f1 100.00
2017-09-23 20:13:54,127:INFO: - new best score!
2017-09-23 20:13:54,127:INFO: Epoch 14 out of 15
2017-09-23 20:18:47,440:INFO: acc 100.00 - f1 100.00
2017-09-23 20:18:49,728:INFO: - new best score!
2017-09-23 20:18:49,728:INFO: Epoch 15 out of 15
2017-09-23 20:23:35,476:INFO: acc 100.00 - f1 100.00
2017-09-23 20:23:37,732:INFO: - new best score!
2017-09-23 22:57:28,311:INFO: Initializing tf session
2017-09-23 22:57:29,975:INFO: Reloading the latest trained model...
2017-09-23 22:57:29,975:INFO: Restoring parameters from results/test/model.weights/
2017-09-23 22:57:30,226:INFO: Testing model over test set
2017-09-23 22:58:32,422:INFO: Initializing tf session
2017-09-23 22:58:37,063:INFO: Reloading the latest trained model...
2017-09-23 22:58:37,063:INFO: Restoring parameters from results/test/model.weights/
2017-09-23 22:58:37,314:INFO: Testing model over test set
2017-09-23 23:00:09,335:INFO: acc 100.00 - f1 100.00
2017-09-23 23:00:09,336:INFO: 
This is an interactive mode.
To exit, enter 'exit'.
You can enter a sentence like
input> I love Paris
2017-09-24 00:01:29,399:INFO: Initializing tf session
2017-09-24 00:01:31,189:INFO: Reloading the latest trained model...
2017-09-24 00:01:31,189:INFO: Restoring parameters from results/test/model.weights/
2017-09-24 00:01:31,436:INFO: Testing model over test set
2017-09-24 00:03:29,427:INFO: acc 100.00 - f1 100.00
2017-09-24 00:03:29,427:INFO: 
This is an interactive mode.
To exit, enter 'exit'.
You can enter a sentence like
input> I love Paris
2017-09-27 17:45:33,784:INFO: Initializing tf session
2017-09-27 17:45:35,252:INFO: Reloading the latest trained model...
2017-09-27 17:45:35,252:INFO: Restoring parameters from nerTagging/results/test/model.weights/
2017-09-27 17:45:35,444:INFO: Testing model over test set
2017-09-27 17:47:00,647:INFO: acc 100.00 - f1 100.00
2017-09-27 17:47:00,663:INFO: 오늘    부산    남구    날씨 어때? 
2017-09-27 17:47:00,663:INFO: B-DTE B-LOC I-LOC O  O   
2017-09-27 17:53:42,797:INFO: Initializing tf session
2017-09-27 17:53:44,327:INFO: Reloading the latest trained model...
2017-09-27 17:53:44,327:INFO: Restoring parameters from nerTagging/results/test/model.weights/
2017-09-27 17:53:44,536:INFO: Testing model over test set
2017-09-27 17:54:59,257:INFO: acc 100.00 - f1 100.00
2017-09-27 17:54:59,287:INFO: 오늘    부산    남구    날씨 어때? 
2017-09-27 17:54:59,287:INFO: B-DTE B-LOC I-LOC O  O   
2017-09-27 17:56:23,710:INFO: Initializing tf session
2017-09-27 17:56:25,140:INFO: Reloading the latest trained model...
2017-09-27 17:56:25,140:INFO: Restoring parameters from nerTagging/results/test/model.weights/
2017-09-27 17:56:25,392:INFO: Testing model over test set
2017-09-27 17:57:46,119:INFO: acc 100.00 - f1 100.00
2017-09-27 18:00:14,307:INFO: Initializing tf session
2017-09-27 18:00:15,832:INFO: Reloading the latest trained model...
2017-09-27 18:00:15,832:INFO: Restoring parameters from nerTagging/results/test/model.weights/
2017-09-27 18:00:16,026:INFO: Testing model over test set
2017-09-27 18:01:38,401:INFO: acc 100.00 - f1 100.00
2017-09-27 20:25:42,753:INFO: Initializing tf session
2017-09-27 20:25:44,873:INFO: Reloading the latest trained model...
2017-09-27 20:25:44,873:INFO: Restoring parameters from nerTagging/results/test/model.weights/
2017-09-27 20:25:45,112:INFO: Testing model over test set
2017-09-27 20:26:59,991:INFO: acc 100.00 - f1 100.00
2017-09-28 01:44:40,037:INFO: Initializing tf session
2017-09-28 01:44:41,411:INFO: Reloading the latest trained model...
2017-09-28 01:44:41,411:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 01:44:41,601:INFO: Testing model over test set
2017-09-28 01:46:00,017:INFO: acc 100.00 - f1 100.00
2017-09-28 02:16:51,629:INFO: Initializing tf session
2017-09-28 02:16:53,008:INFO: Reloading the latest trained model...
2017-09-28 02:16:53,008:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 02:16:53,249:INFO: Testing model over test set
2017-09-28 02:18:02,196:INFO: acc 100.00 - f1 100.00
2017-09-28 02:22:56,830:INFO: Initializing tf session
2017-09-28 02:22:58,226:INFO: Reloading the latest trained model...
2017-09-28 02:22:58,226:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 02:22:58,420:INFO: Testing model over test set
2017-09-28 02:24:05,205:INFO: acc 100.00 - f1 100.00
2017-09-28 02:44:35,845:INFO: Initializing tf session
2017-09-28 02:44:37,307:INFO: Reloading the latest trained model...
2017-09-28 02:44:37,307:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 02:44:37,591:INFO: Testing model over test set
2017-09-28 02:45:52,171:INFO: acc 100.00 - f1 100.00
2017-09-28 02:48:33,188:INFO: Initializing tf session
2017-09-28 02:48:34,842:INFO: Reloading the latest trained model...
2017-09-28 02:48:34,842:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 02:48:35,138:INFO: Testing model over test set
2017-09-28 02:49:54,374:INFO: acc 100.00 - f1 100.00
2017-09-28 03:01:18,105:INFO: Initializing tf session
2017-09-28 03:01:19,536:INFO: Reloading the latest trained model...
2017-09-28 03:01:19,536:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:01:19,819:INFO: Testing model over test set
2017-09-28 03:02:47,331:INFO: acc 100.00 - f1 100.00
2017-09-28 03:13:23,287:INFO: Initializing tf session
2017-09-28 03:13:24,953:INFO: Reloading the latest trained model...
2017-09-28 03:13:24,953:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:13:25,283:INFO: Testing model over test set
2017-09-28 03:14:45,142:INFO: acc 100.00 - f1 100.00
2017-09-28 03:29:28,454:INFO: Initializing tf session
2017-09-28 03:29:30,197:INFO: Reloading the latest trained model...
2017-09-28 03:29:30,197:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:29:30,446:INFO: Testing model over test set
2017-09-28 03:30:58,298:INFO: acc 100.00 - f1 100.00
2017-09-28 03:30:58,300:INFO: loading Word2Vec object from classification/w2vTypeModel
2017-09-28 03:30:58,306:INFO: loading wv recursively from classification/w2vTypeModel.wv.* with mmap=None
2017-09-28 03:30:58,307:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:30:58,308:INFO: setting ignored attribute cum_table to None
2017-09-28 03:30:58,308:INFO: loaded classification/w2vTypeModel
2017-09-28 03:31:01,243:INFO: loading Word2Vec object from classification/날씨_w2vIntentModel
2017-09-28 03:31:01,247:INFO: loading wv recursively from classification/날씨_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:31:01,247:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:31:01,247:INFO: setting ignored attribute cum_table to None
2017-09-28 03:31:01,247:INFO: loaded classification/날씨_w2vIntentModel
2017-09-28 03:31:01,297:INFO: loading Word2Vec object from classification/음악_w2vIntentModel
2017-09-28 03:31:01,298:INFO: loading wv recursively from classification/음악_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:31:01,299:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:31:01,299:INFO: setting ignored attribute cum_table to None
2017-09-28 03:31:01,299:INFO: loaded classification/음악_w2vIntentModel
2017-09-28 03:31:01,349:INFO: loading Word2Vec object from classification/메모_w2vIntentModel
2017-09-28 03:31:01,364:INFO: loading wv recursively from classification/메모_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:31:01,403:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:31:01,403:INFO: setting ignored attribute cum_table to None
2017-09-28 03:31:01,403:INFO: loaded classification/메모_w2vIntentModel
2017-09-28 03:31:01,465:INFO: loading Word2Vec object from classification/알람_w2vIntentModel
2017-09-28 03:31:01,467:INFO: loading wv recursively from classification/알람_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:31:01,468:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:31:01,468:INFO: setting ignored attribute cum_table to None
2017-09-28 03:31:01,468:INFO: loaded classification/알람_w2vIntentModel
2017-09-28 03:35:25,178:INFO: Initializing tf session
2017-09-28 03:35:26,763:INFO: Reloading the latest trained model...
2017-09-28 03:35:26,763:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:35:26,983:INFO: Testing model over test set
2017-09-28 03:36:40,648:INFO: acc 100.00 - f1 100.00
2017-09-28 03:36:40,648:INFO: loading Word2Vec object from classification/w2vTypeModel
2017-09-28 03:36:40,652:INFO: loading wv recursively from classification/w2vTypeModel.wv.* with mmap=None
2017-09-28 03:36:40,652:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:36:40,652:INFO: setting ignored attribute cum_table to None
2017-09-28 03:36:40,652:INFO: loaded classification/w2vTypeModel
2017-09-28 03:36:42,622:INFO: loading Word2Vec object from classification/날씨_w2vIntentModel
2017-09-28 03:36:42,624:INFO: loading wv recursively from classification/날씨_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:36:42,624:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:36:42,624:INFO: setting ignored attribute cum_table to None
2017-09-28 03:36:42,624:INFO: loaded classification/날씨_w2vIntentModel
2017-09-28 03:36:42,660:INFO: loading Word2Vec object from classification/음악_w2vIntentModel
2017-09-28 03:36:42,661:INFO: loading wv recursively from classification/음악_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:36:42,661:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:36:42,661:INFO: setting ignored attribute cum_table to None
2017-09-28 03:36:42,661:INFO: loaded classification/음악_w2vIntentModel
2017-09-28 03:36:42,680:INFO: loading Word2Vec object from classification/메모_w2vIntentModel
2017-09-28 03:36:42,682:INFO: loading wv recursively from classification/메모_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:36:42,682:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:36:42,682:INFO: setting ignored attribute cum_table to None
2017-09-28 03:36:42,682:INFO: loaded classification/메모_w2vIntentModel
2017-09-28 03:36:42,692:INFO: loading Word2Vec object from classification/알람_w2vIntentModel
2017-09-28 03:36:42,693:INFO: loading wv recursively from classification/알람_w2vIntentModel.wv.* with mmap=None
2017-09-28 03:36:42,693:INFO: setting ignored attribute syn0norm to None
2017-09-28 03:36:42,694:INFO: setting ignored attribute cum_table to None
2017-09-28 03:36:42,694:INFO: loaded classification/알람_w2vIntentModel
2017-09-28 03:46:01,110:INFO: Initializing tf session
2017-09-28 03:46:02,587:INFO: Reloading the latest trained model...
2017-09-28 03:46:02,587:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:46:31,152:INFO: Initializing tf session
2017-09-28 03:46:32,559:INFO: Reloading the latest trained model...
2017-09-28 03:46:32,559:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 03:48:25,063:INFO: Initializing tf session
2017-09-28 03:48:26,491:INFO: Reloading the latest trained model...
2017-09-28 03:48:26,491:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:00:56,972:INFO: Initializing tf session
2017-09-28 04:00:58,568:INFO: Reloading the latest trained model...
2017-09-28 04:00:58,569:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:01:45,929:INFO: Initializing tf session
2017-09-28 04:01:47,537:INFO: Reloading the latest trained model...
2017-09-28 04:01:47,537:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:02:23,337:INFO: Initializing tf session
2017-09-28 04:02:24,717:INFO: Reloading the latest trained model...
2017-09-28 04:02:24,717:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:02:40,046:INFO: Initializing tf session
2017-09-28 04:02:41,536:INFO: Reloading the latest trained model...
2017-09-28 04:02:41,537:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:04:10,100:INFO: Initializing tf session
2017-09-28 04:04:11,477:INFO: Reloading the latest trained model...
2017-09-28 04:04:11,477:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:04:25,855:INFO: Initializing tf session
2017-09-28 04:04:27,286:INFO: Reloading the latest trained model...
2017-09-28 04:04:27,287:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:07:21,221:INFO: Initializing tf session
2017-09-28 04:07:25,149:INFO: Reloading the latest trained model...
2017-09-28 04:07:25,152:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:38:44,921:INFO: Initializing tf session
2017-09-28 04:38:46,781:INFO: Reloading the latest trained model...
2017-09-28 04:38:46,781:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:39:16,568:INFO: Initializing tf session
2017-09-28 04:39:18,996:INFO: Reloading the latest trained model...
2017-09-28 04:39:18,996:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:41:25,068:INFO: Initializing tf session
2017-09-28 04:41:26,731:INFO: Reloading the latest trained model...
2017-09-28 04:41:26,731:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:41:44,009:INFO: Initializing tf session
2017-09-28 04:41:45,693:INFO: Reloading the latest trained model...
2017-09-28 04:41:45,693:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:45:35,811:INFO: Initializing tf session
2017-09-28 04:45:37,733:INFO: Reloading the latest trained model...
2017-09-28 04:45:37,733:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:45:59,087:INFO: Initializing tf session
2017-09-28 04:46:00,879:INFO: Reloading the latest trained model...
2017-09-28 04:46:00,880:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:51:24,857:INFO: Initializing tf session
2017-09-28 04:51:26,581:INFO: Reloading the latest trained model...
2017-09-28 04:51:26,581:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:51:45,479:INFO: Initializing tf session
2017-09-28 04:51:47,824:INFO: Reloading the latest trained model...
2017-09-28 04:51:47,824:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:52:02,765:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 12, in getSentence
    type = TYPE_INSTANCE.testing(sentence).split('/')[0]
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/classification/typeClassification.py", line 136, in testing
    tokenizedWords = self.tokenize(newSentence)['tokenizedWords']
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/classification/typeClassification.py", line 17, in tokenize
    jpype.startJVM(p)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/jpype/_core.py", line 44, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to start JVM at src/native/common/jp_env.cpp:60
2017-09-28 04:52:09,756:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 12, in getSentence
    type = TYPE_INSTANCE.testing(sentence).split('/')[0]
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/classification/typeClassification.py", line 136, in testing
    tokenizedWords = self.tokenize(newSentence)['tokenizedWords']
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/classification/typeClassification.py", line 17, in tokenize
    jpype.startJVM(p)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/jpype/_core.py", line 44, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to start JVM at src/native/common/jp_env.cpp:60
2017-09-28 04:53:43,977:INFO: Initializing tf session
2017-09-28 04:53:45,649:INFO: Reloading the latest trained model...
2017-09-28 04:53:45,649:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:54:29,584:INFO: Initializing tf session
2017-09-28 04:54:32,267:INFO: Reloading the latest trained model...
2017-09-28 04:54:32,267:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:54:54,664:INFO: Initializing tf session
2017-09-28 04:54:56,237:INFO: Reloading the latest trained model...
2017-09-28 04:54:56,238:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:55:03,211:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view api.views.getSentence didn't return an HttpResponse object. It returned None instead.
2017-09-28 04:55:56,018:INFO: Initializing tf session
2017-09-28 04:55:57,589:INFO: Reloading the latest trained model...
2017-09-28 04:55:57,590:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 04:56:40,327:INFO: Initializing tf session
2017-09-28 04:56:42,232:INFO: Reloading the latest trained model...
2017-09-28 04:56:42,232:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:03:20,041:INFO: Initializing tf session
2017-09-28 05:03:21,881:INFO: Reloading the latest trained model...
2017-09-28 05:03:21,882:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:03:51,042:INFO: Initializing tf session
2017-09-28 05:03:53,046:INFO: Reloading the latest trained model...
2017-09-28 05:03:53,046:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:04:49,290:INFO: Initializing tf session
2017-09-28 05:04:51,129:INFO: Reloading the latest trained model...
2017-09-28 05:04:51,129:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:05:18,195:INFO: Initializing tf session
2017-09-28 05:05:19,817:INFO: Reloading the latest trained model...
2017-09-28 05:05:19,817:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:07:12,510:INFO: Initializing tf session
2017-09-28 05:07:14,435:INFO: Reloading the latest trained model...
2017-09-28 05:07:14,435:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:07:39,174:INFO: Initializing tf session
2017-09-28 05:07:40,776:INFO: Reloading the latest trained model...
2017-09-28 05:07:40,776:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:08:06,368:INFO: Initializing tf session
2017-09-28 05:08:08,211:INFO: Reloading the latest trained model...
2017-09-28 05:08:08,211:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:09:27,082:INFO: Initializing tf session
2017-09-28 05:09:28,972:INFO: Reloading the latest trained model...
2017-09-28 05:09:28,972:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:09:58,672:INFO: Initializing tf session
2017-09-28 05:10:00,441:INFO: Reloading the latest trained model...
2017-09-28 05:10:00,441:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:10:57,788:INFO: Initializing tf session
2017-09-28 05:10:59,749:INFO: Reloading the latest trained model...
2017-09-28 05:10:59,749:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:11:34,283:INFO: Initializing tf session
2017-09-28 05:11:36,167:INFO: Reloading the latest trained model...
2017-09-28 05:11:36,167:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:12:28,291:INFO: Initializing tf session
2017-09-28 05:12:30,242:INFO: Reloading the latest trained model...
2017-09-28 05:12:30,242:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:13:35,685:INFO: Initializing tf session
2017-09-28 05:13:37,812:INFO: Reloading the latest trained model...
2017-09-28 05:13:37,812:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:14:02,087:INFO: Initializing tf session
2017-09-28 05:14:03,906:INFO: Reloading the latest trained model...
2017-09-28 05:14:03,906:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:14:06,446:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 14, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 18, in getSentence
    except request.GET['sentence'].DoesNotExist as e:
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"
2017-09-28 05:14:07,026:WARNING: Not Found: /favicon.ico
2017-09-28 05:15:03,484:INFO: Initializing tf session
2017-09-28 05:15:05,079:INFO: Reloading the latest trained model...
2017-09-28 05:15:05,080:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:15:08,361:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 14, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 18, in getSentence
    except django.utils.datastructures.MultiValueDictKeyError as e:
NameError: name 'django' is not defined
2017-09-28 05:15:42,140:INFO: Initializing tf session
2017-09-28 05:15:44,381:INFO: Reloading the latest trained model...
2017-09-28 05:15:44,381:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:16:11,139:INFO: Initializing tf session
2017-09-28 05:16:12,862:INFO: Reloading the latest trained model...
2017-09-28 05:16:12,862:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:16:22,586:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 15, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 20, in getSentence
    return JsonResponse({'code': 400, 'error': e, 'message': 'Request Has Not a Sentence'})
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultiValueDictKeyError' is not JSON serializable
2017-09-28 05:17:12,223:INFO: Initializing tf session
2017-09-28 05:17:14,016:INFO: Reloading the latest trained model...
2017-09-28 05:17:14,018:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:17:38,296:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 14, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 19, in getSentence
    return JsonResponse({'code': 400, 'error': e, 'message': 'Request Has Not a Sentence'})
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/var/pyenv/versions/myenv/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultiValueDictKeyError' is not JSON serializable
2017-09-28 05:18:17,560:INFO: Initializing tf session
2017-09-28 05:18:19,425:INFO: Reloading the latest trained model...
2017-09-28 05:18:19,425:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:18:40,095:INFO: Initializing tf session
2017-09-28 05:18:42,056:INFO: Reloading the latest trained model...
2017-09-28 05:18:42,057:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:18:50,143:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 14, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 19, in getSentence
    return JsonResponse({'code': 400, 'error': e, 'message': 'Request Has Not a Sentence'})
  File "/usr/local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultiValueDictKeyError' is not JSON serializable
2017-09-28 05:21:42,089:INFO: Initializing tf session
2017-09-28 05:21:43,828:INFO: Reloading the latest trained model...
2017-09-28 05:21:43,828:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:22:04,052:INFO: Initializing tf session
2017-09-28 05:22:05,930:INFO: Reloading the latest trained model...
2017-09-28 05:22:05,930:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:22:10,499:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 13, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 19, in getSentence
    return JsonResponse({'code': 400, 'error': e, 'message': 'Request Has Not a Sentence'})
  File "/usr/local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultiValueDictKeyError' is not JSON serializable
2017-09-28 05:23:32,708:INFO: Initializing tf session
2017-09-28 05:23:36,003:INFO: Reloading the latest trained model...
2017-09-28 05:23:36,003:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:23:58,259:INFO: Initializing tf session
2017-09-28 05:24:00,171:INFO: Reloading the latest trained model...
2017-09-28 05:24:00,171:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:24:19,968:INFO: Initializing tf session
2017-09-28 05:24:21,782:INFO: Reloading the latest trained model...
2017-09-28 05:24:21,782:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:26:37,984:INFO: Initializing tf session
2017-09-28 05:26:40,466:INFO: Reloading the latest trained model...
2017-09-28 05:26:40,467:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:27:03,024:INFO: Initializing tf session
2017-09-28 05:27:04,985:INFO: Reloading the latest trained model...
2017-09-28 05:27:04,985:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:27:35,627:INFO: Initializing tf session
2017-09-28 05:27:37,341:INFO: Reloading the latest trained model...
2017-09-28 05:27:37,342:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:27:51,081:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'sentence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 14, in getSentence
    sentence = request.GET['sentence']
  File "/usr/local/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'sentence'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 20, in getSentence
    return HttpResponse(json.dumps(res), content_type="application/json")
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultiValueDictKeyError' is not JSON serializable
2017-09-28 05:29:08,964:INFO: Initializing tf session
2017-09-28 05:29:10,792:INFO: Reloading the latest trained model...
2017-09-28 05:29:10,793:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:29:30,286:INFO: Initializing tf session
2017-09-28 05:29:32,093:INFO: Reloading the latest trained model...
2017-09-28 05:29:32,093:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:30:14,172:INFO: Initializing tf session
2017-09-28 05:30:16,339:INFO: Reloading the latest trained model...
2017-09-28 05:30:16,339:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:31:44,156:INFO: Initializing tf session
2017-09-28 05:31:46,175:INFO: Reloading the latest trained model...
2017-09-28 05:31:46,175:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:33:01,632:INFO: Initializing tf session
2017-09-28 05:33:03,458:INFO: Reloading the latest trained model...
2017-09-28 05:33:03,458:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:34:03,185:INFO: Initializing tf session
2017-09-28 05:34:05,301:INFO: Reloading the latest trained model...
2017-09-28 05:34:05,301:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:34:56,370:INFO: Initializing tf session
2017-09-28 05:34:58,739:INFO: Reloading the latest trained model...
2017-09-28 05:34:58,739:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:36:10,910:INFO: Initializing tf session
2017-09-28 05:36:13,216:INFO: Reloading the latest trained model...
2017-09-28 05:36:13,216:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:37:49,593:INFO: Initializing tf session
2017-09-28 05:37:51,569:INFO: Reloading the latest trained model...
2017-09-28 05:37:51,569:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:39:11,642:INFO: Initializing tf session
2017-09-28 05:39:14,110:INFO: Reloading the latest trained model...
2017-09-28 05:39:14,111:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:39:48,198:INFO: Initializing tf session
2017-09-28 05:39:50,130:INFO: Reloading the latest trained model...
2017-09-28 05:39:50,130:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:41:44,579:INFO: Initializing tf session
2017-09-28 05:41:46,336:INFO: Reloading the latest trained model...
2017-09-28 05:41:46,336:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:42:30,124:INFO: Initializing tf session
2017-09-28 05:42:32,083:INFO: Reloading the latest trained model...
2017-09-28 05:42:32,083:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:43:03,365:INFO: Initializing tf session
2017-09-28 05:43:05,638:INFO: Reloading the latest trained model...
2017-09-28 05:43:05,638:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:43:41,986:INFO: Initializing tf session
2017-09-28 05:43:44,372:INFO: Reloading the latest trained model...
2017-09-28 05:43:44,372:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:44:17,693:INFO: Initializing tf session
2017-09-28 05:44:19,411:INFO: Reloading the latest trained model...
2017-09-28 05:44:19,411:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:45:25,601:INFO: Initializing tf session
2017-09-28 05:45:27,265:INFO: Reloading the latest trained model...
2017-09-28 05:45:27,265:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:46:02,389:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 26, in getSentence
    dateWords.push(NER_sent[idx])
AttributeError: 'list' object has no attribute 'push'
2017-09-28 05:46:57,064:INFO: Initializing tf session
2017-09-28 05:46:59,074:INFO: Reloading the latest trained model...
2017-09-28 05:46:59,074:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:47:03,961:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 24, in getSentence
    dateWords.push(NER_sent[idx])
AttributeError: 'list' object has no attribute 'push'
2017-09-28 05:47:06,626:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 24, in getSentence
    dateWords.push(NER_sent[idx])
AttributeError: 'list' object has no attribute 'push'
2017-09-28 05:48:03,230:INFO: Initializing tf session
2017-09-28 05:48:05,352:INFO: Reloading the latest trained model...
2017-09-28 05:48:05,352:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:48:12,589:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 24, in getSentence
    dateWords.push(NER_sent[idx])
AttributeError: 'list' object has no attribute 'push'
2017-09-28 05:48:49,627:INFO: Initializing tf session
2017-09-28 05:48:51,471:INFO: Reloading the latest trained model...
2017-09-28 05:48:51,471:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:48:56,738:ERROR: Internal Server Error: /api/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gujinhyeon/Desktop/dev/졸업과제/mybiseo/mybiseoServer/api/views.py", line 25, in getSentence
    while NER_tag[idx+1] != 'I-DTE':
IndexError: list index out of range
2017-09-28 05:51:16,141:INFO: Initializing tf session
2017-09-28 05:51:18,079:INFO: Reloading the latest trained model...
2017-09-28 05:51:18,079:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:51:59,199:INFO: Initializing tf session
2017-09-28 05:52:01,018:INFO: Reloading the latest trained model...
2017-09-28 05:52:01,019:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 05:53:25,442:INFO: Initializing tf session
2017-09-28 05:53:27,223:INFO: Reloading the latest trained model...
2017-09-28 05:53:27,223:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 09:26:14,206:INFO: Initializing tf session
2017-09-28 09:26:16,951:INFO: Reloading the latest trained model...
2017-09-28 09:26:16,951:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
2017-09-28 09:27:09,402:INFO: Initializing tf session
2017-09-28 09:27:11,599:INFO: Reloading the latest trained model...
2017-09-28 09:27:11,600:INFO: Restoring parameters from classification/nerTagging/results/test/model.weights/
